WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "D:\Мансур\Python\Urban\tests_12_4.py", line 68, in test_run
    runner = Runner(123, 10)
             ^^^^^^^^^^^^^^^
  File "D:\Мансур\Python\Urban\tests_12_4.py", line 13, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "D:\Мансур\Python\Urban\tests_12_4.py", line 60, in test_walk
    runner = Runner('Вася', -5)
             ^^^^^^^^^^^^^^^^^^
  File "D:\Мансур\Python\Urban\tests_12_4.py", line 18, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
